[project]
name = "gs-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "google-generativeai>=0.8.5",
    "python-decouple>=3.8",
    "uvicorn[standard]>=0.38.0",
]
